development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://eriygvtqmdhmtd:MSuYsMdjIk9acmtZMLP16JdlMi@ec2-54-243-63-195.compute-1.amazonaws.com:5432/df438ed0r18doo
